### ISSUE TITLE
"Create script" not possible

### ISSUE THREAD

**Issue by klassikmann** [rern/rOS#1]
**First try of diy-rOS**

Script download with
`bash <( wget -qO - https://github.com/rern/rOS/raw/master/create-alarm.sh )`
not possible. 
Possible bypass: Change URL to
`bash <( wget -qO - https://raw.githubusercontent.com/rern/rOS/main/create-alarm.sh )`

EDIT: After changing the URL die generation of the system ran straight-forward.

**Comment by rern** [comment]
Fixed.
Default branch has changed from `master` to `main` recently.

rern
