### ISSUE TITLE
A recent version of spotifyd (gapless playback) for rOS

### ISSUE THREAD

**Issue by daoane** [rern/rOS#5]
Playback with spotifyd <v0.3 can get very annoying because of the forced gap of ~3 seconds between all songs. Spotifyd >v0.3 supports gapless playback by default. However, the Archlinux repositorys provide only v0.2.x - like 0.2.24 that is installed with rOS/rAudio-1. **An upgrade to a recent version is pretty easy and works fine:**
* Download the latest version here: https://github.com/Spotifyd/spotifyd/releases
* move /usr/bin/spotifyd to /user/bin/spotifyd.bak and move put the downloaded spotifyd into /usr/bin (change owner to root)
* edit /etc/spotifyd.conf and add quotation marks around the values of *device* and *on_song_change_hook* (else the service will fail), add `use_mpris = false` to avoid dbus bind error ~~and possibly a cache directory to facility preload of next song for gapless play, e.g. `cache_path = "/root/.cache/spotifyd"`(though I'm not sure if this is really required)~~ Edit: it works reasonably well without cache and RuneAudio displays the album cover in sync with the cache loading, not with the playback, so best to avoid.
* restart spotifyd

How can this be included in rOS to make it available to all users? Spotifyd can be easily added in /usr/bin, but I'm lost with the configuration of the ArchLinux installation. Where is the configuration that installs spotifyd from the repositories (and which in the case above should be removed)?

**Comment by rern** [comment]
Actually, official repo has `spotifyd 3.2` but it has some bugs.
~~You may download an updated image file which has `v3.0` installed.~~
rOS has `v3.0` installed.

**Comment by daoane** [comment]
I could only find x86_64 at Archlinux, but now I see that there is a package elsewhere (pkgs.org). It's much smaller than even the slim version at Spotidfyd-Github. I assume it includes dependencies and maybe that is why it works flawlessly until now (I have installed the full version) The only problem is that rAudio-1(?) seems to overwrite the device line in the configuration file without quotation marks (temporarly fixed with 444 permission), which prevents Spotifyd (Spotifyd-Github) from starting - I don't know if this would also be an issue with the pkgs-spotifyd 0.3.2. I can try over the Easter holidays.
