### ISSUE TITLE
A more friendly install process

### ISSUE THREAD

**Issue by AskAlice** [rern/rOS#6]
I am not interested in installing arch just to flash something onto my raspberry pi.
Could you make actual releases that flash with the official pi flasher?

**Comment by rern** [comment]
At the very first line of the [first page / readme](https://github.com/rern/rOS#ros---diy-raudio):

Build [rAudio](https://github.com/rern/rAudio-1) - Audio player and renderer for Raspberry Pi
...

(The link: https://github.com/rern/rAudio-1)
